version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnr-api
    container_name: cnr-api
    env_file: .env
    ports:
      - "8000:$SERVER_PORT"
    
    